services:
  promo:
    build:
      context: ..
      dockerfile: ./apps/promo/Dockerfile
    container_name: fod-promo-${COMPOSE_ENV:-dev}
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      PORT: ${PROMO_PORT:-3000}
    restart: unless-stopped

